languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "JujinKim.com"
copyright = "© Jujin Kim, 1992 ~ Current"

[params]
  dateFormat = "2 January 2006"
  description = "Jujin Kim's profile webpage and blog"