# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# For texify3 theme, use name, url/pageRef, and weight parameters.
# Optional: pre parameter for SVG icons

[[main]]
  pre = '<i class="fas fa-blog"></i>'
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  pre = '<i class="fas fa-tags"></i>'
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[main]]
  pre = '<i class="fas fa-user"></i>'
  name = "About"
  url = "/about/"
  weight = 30

[[main]]
  pre = '<i class="fab fa-github"></i>'
  name = "GitHub"
  url = "https://github.com/jujinkim"
  weight = 40