baseURL = "https://jujinkim.com"
title = "Jujin Kim's"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
hasCJKLanguage = true
copyright = "Jujin Kim"
googleAnalytics = "UA-54002449-3"
enableRobotsTXT = true
enableEmoji = true

[markup.highlight]
style = "github-dark"

[params]
  author = "Jujin Kim"
  info = "Software developer"
  description = "Jujin's personal website"
  keywords = "blog,developer,personal"
  #avatarurl = "images/avatar.jpg"
  gravatar = "jujin@jujinkim.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 1992

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
    name = "About"
    icon = "fa fa-user fa-2x"
    weight = 1
    url = "../me"
[[params.social]]
    name = "Devlog"
    icon = "fa fa-code fa-2x"
    weight = 2
    url = "https://jujin.dev"
[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 3
    url = "https://github.com/jujinkim/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin fa-2x"
    weight = 4
    url = "https://www.linkedin.com/in/jujinkim/"
[[params.social]]
    name = "Instagram"
    icon = "fa fa-instagram fa-2x"
    weight = 5
    url = "https://www.instagram.com/jujin__kim/"
[[params.social]]
    name = "Facebook"
    icon = "fa fa-facebook fa-2x"
    weight = 6
    url = "https://www.facebook.com/jujinjujinjujin"
[[params.social]]
    name = "Email"
    icon = "fa fa-envelope fa-2x"
    weight = 7
    url = "mailto:jujin@jujinkim.com"

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/post/"
        weight = 1
    [[menu.main]]
        identifier = "about"
        name = "About me"
        url = "../me"
        weight = 2

[params.utterances]
  repo = "jujinkim/web-jujinkim.com-comment" # https://utteranc.es/#heading-repository
  issueTerm = "pathname" # https://utteranc.es/#heading-mapping
  label = "comment" # https://utteranc.es/#heading-issue-label
  theme = "preferred-color-scheme" # https://utteranc.es/#heading-theme