baseURL = "https://jujinkim.com"
DefaultContentLanguage = "en"
theme = "tale"
hasCJKLanguage = true
copyright = "Jujin Kim (Dangumju)"

[languages]
    [languages.ko]
        title = "김주진 블로그"
        languageName = "한국어"
    [languages.en]
        title = "Jujin Kim's blog"
        languageName = "English"