baseURL = "https://jujinkim.com"
DefaultContentLanguage = "en"
theme = "hugo-PaperMod"
hasCJKLanguage = true
copyright = "Jujin Kim (Dangumju)"
googleAnalytics = "UA-54002449-3"

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About me"
        url = "/me"
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/post"

[params]
    defaultTheme = "auto"
    layout = "archives"
    ShowShareButtons = true
    ShowReadingTime = true
    ShowToc = true
    TocOpen = true
    comments = true
    [homeInfoParams]
        Title = "Hi there wave"
        Content = "Can be Info, links, about..."

[languages]
    [languages.ko]
        title = "김주진 블로그"
        languageName = "한국어"
    [languages.en]
        title = "Jujin Kim's blog"
        languageName = "English"